from lxml import etree

page = etree.Element('html')
doc = etree.ElementTree(page)
#metacomment = etree.Comment(text = 'META tag comment')
#page.append(metacomment)

metaE = etree.SubElement(page, 'meta')
#metacomment = etree.Comment(text = 'META tag comment')
#metaE.append(metacomment)
resourceE = etree.SubElement(metaE, 'resource')
typeE = etree.SubElement(resourceE, 'type')
idE = etree.SubElement(resourceE, 'id')
idE.set('type', 'isbn-10')
idE.set('value', '123456789')

resource_urlE = etree.SubElement(resourceE, 'url')
resource_urlE.set('site','amazon.com' )
siteE = etree.SubElement(metaE, 'site')
sourceE = etree.SubElement(metaE, 'source')
dl_dateE = etree.SubElement(metaE, 'download-date')


bookE = etree.SubElement(page, 'book')
bookE.set('structure_version', '1')
#bookcomment = etree.Comment(text = 'BOOK tag comment')
#bookE.append(bookcomment)
titleE = etree.SubElement(bookE, 'title')
contentE = etree.SubElement(bookE, 'content')
imagesE = etree.SubElement(bookE, 'images')
itemE = etree.SubElement(imagesE, 'item')
detailsE = etree.SubElement(bookE, 'details')
releaseE = etree.SubElement(detailsE, 'release')
formatE = etree.SubElement(detailsE, 'format')
formatE.set('type', 'paperback/ebook')
pagesE = etree.SubElement(formatE, 'pages')
sizeE = etree.SubElement(formatE, 'size')
authorE = etree.SubElement(detailsE, 'author')
languageE = etree.SubElement(detailsE, 'language')
isbnE = etree.SubElement(detailsE, 'isbn')
itemE = etree.SubElement(isbnE, 'item')
item1E = etree.SubElement(isbnE, 'item')
itemE.set('type', 'ISBN-10')
itemE.set('value', '123456789')
item1E.set('type', 'ISBN-13')
item1E.set('value', 'ISBN-13-123456789')

categoriesE = etree.SubElement(bookE, 'categories')
tagE = etree.SubElement(bookE, 'tag')
downloadE = etree.SubElement(bookE, 'download')
linkE = etree.SubElement(downloadE, 'link')
textE = etree.SubElement(linkE, 'text')
dl_urlE = etree.SubElement(linkE, 'url')
text2E = etree.SubElement(linkE, 'text2')

file = open('ebook.xml', 'w')
doc.write(file)
file.close()
