from lxml import etree

page = etree.Element('html')
doc = etree.ElementTree(page)

metaE = etree.SubElement(page, 'meta')
resourceE = etree.SubElement(metaE, 'resource')
typeE = etree.SubElement(resourceE, 'type')
idE = etree.SubElement(resourceE, 'id')
idE.set('type', 'isbn-10')
idE.set('value', '123456789')

resource_urlE = etree.SubElement(resourceE, 'url')
resource_urlE.set('site', 'amazon.com' )
siteE = etree.SubElement(metaE, 'site')
siteE.text = 'www.wowebook.be'
sourceE = etree.SubElement(metaE, 'source')
dl_dateE = etree.SubElement(metaE, 'download-date')


bookE = etree.SubElement(page, 'book')
bookE.set('structure_version', '1')
titleE = etree.SubElement(bookE, 'title')
contentE = etree.SubElement(bookE, 'content')
imagesE = etree.SubElement(bookE, 'images')
images_itemE = etree.SubElement(imagesE, 'item')
detailsE = etree.SubElement(bookE, 'details')
releaseE = etree.SubElement(detailsE, 'release')
formatE = etree.SubElement(detailsE, 'format')
formatE.set('type', 'paperback/ebook')
pagesE = etree.SubElement(formatE, 'pages')
sizeE = etree.SubElement(formatE, 'size')
authorE = etree.SubElement(detailsE, 'author')
languageE = etree.SubElement(detailsE, 'language')
isbnE = etree.SubElement(detailsE, 'isbn')
isbn_itemE = etree.SubElement(isbnE, 'item')
isbn_item1E = etree.SubElement(isbnE, 'item')
isbn_itemE.set('type', 'ISBN-10')
isbn_itemE.set('value', '123456789')
isbn_item1E.set('type', 'ISBN-13')
isbn_item1E.set('value', 'ISBN-13-123456789')

categoriesE = etree.SubElement(bookE, 'categories')
downloadE = etree.SubElement(bookE, 'download')
linkE = etree.SubElement(downloadE, 'link')
textE = etree.SubElement(linkE, 'text')
dl_urlE = etree.SubElement(linkE, 'url')
text2E = etree.SubElement(linkE, 'text2')
